version : "3.7"
services :
      flaskapp :
          build : .
          volumes : 
            - .:/tdnote2
          ports : 
            - "5000:5000"
          links:
            - "postgres:db"
          depends_on : 
            - postgres
          environment : 
            SECRET_KEY: mysecretkey
            USE_POSTGRES: 'true'
            POSTGRES_PASSWORD: POSTGRES_PASSWORD
            POSTGRES_USER: POSTGRES_USER
            POSTGRES_DB: POSTGRES_DB
      postgres : 
        image : "postgres:latest"
        environment : 
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
          POSTGRES_USER: POSTGRES_USER
          POSTGRES_DB: POSTGRES_DB
        restart : always
          

          

